name: Deploy Lambda Function

on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
      S3_BUCKET_NAME: resume-api-lambda
      LAMBDA: resume-lambda-code

jobs:
  package:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Zip Lambda code
        run: |
          zip -r ${{ env.LAMBDA }}.zip api/resume-lambda-code.py

      - name: Upload Lambda code to S3
        run: |
          aws s3 cp ${{ env.LAMBDA }}.zip s3://${{ env.S3_BUCKET_NAME }}/${{ env.LAMBDA }}.zip
        

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [package]

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code --function-name ${{ env.LAMBDA }} --s3-bucket ${{ env.S3_BUCKET_NAME }} --s3-key ${{ env.LAMBDA }}.zip
