name: Deploy Lambda Function

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  package:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      S3_BUCKET_NAME: resume-api-lambda
      LAMBDA: resume-lambda-code.zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List directory contents
        run: ls -la # Debugging step

      - name: Zip Lambda code
        run: |
          zip -r ${{ env.LAMBDA }}.zip api/resume-lambda-code.py

      - name: Upload Lambda code to S3
        run: |
          aws s3 cp ${{ env.LAMBDA }}.zip s3://${{ env.S3_BUCKET_NAME }}/${{ env.LAMBDA }}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [package]

    env:
      S3_BUCKET_NAME: resume-api-lambda
      LAMBDA_CODE_FILE: resume-lambda-code.zip
      LAMBDA_FUNCTION_NAME: resume_function

    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA }} \
            --s3-bucket ${{ env.S3_BUCKET_NAME }} --s3-key ${{ env.LAMBDA }}.zip
