name: Deploy Lambda Function

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  package:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip Lambda code
        run: |
          zip -r resume-lambda-code.zip C:\Users\thelm\Desktop\me\AWS Projects\AWS Cloud Resume-Json\api\resume-lambda-code.py

      - name: Upload Lambda code to S3
        run: |
          aws s3 cp resume-lambda-code.zip s3://resume-api-lambda/resume-lambda-code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [package]

    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download Lambda code from S3
        run: |
          aws s3 cp s3://resume-api-lambda/resume-lambda-code.zip resume-lambda-code.zip

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name resume_function \
            --zip-file fileb://resume-lambda-code.zip
